kind: almanac
format: "{language.strings.sunrise} {plugin-data.sunrise:%H:%M} {language.strings.sunset} {plugin-data.sunset:%H:%M} {language.strings.moon_phase} {plugin-data.moonphase}"

# no times, since on such a day the format above would print its own braces
polar-format: "{plugin-data.sun} {language.strings.moon_phase} {plugin-data.moonphase}"
location:
    latitude: "{location.latitude}"
    longitude: "{location.longitude}"
    timezone: "{location.timezone}"
    elevation: "{location.elevation}"
